### ISSUE TITLE
[Jennifer Atance] w4-ETL-Project

### ISSUE THREAD

**Issue by jenatance** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#1]
https://github.com/jenatance/myLeagueOfLegends

**Comment by Gobuub** [comment]
Muy buen trabajo para hacerlo en las condiciones que has estado este finde, y sin haber podido venir a clase durante los "días clave", bien hecho jenni, el readme estaría mejor que pusieras el tuyo propio explicando de que va tu proyecto, con tus resultados, mas que el readme general de lo que iba el lab de la semana, solo por comentar un pequeño matiz ;).
