### ISSUE TITLE
[Irene Aguerri] ETL Project

### ISSUE THREAD

**Issue by iaguerri** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#2]
https://github.com/iaguerri/ETL_ih

**Comment by Gobuub** [comment]
No me funciona tu link
![Captura de pantalla 2022-06-28 105653](https://user-images.githubusercontent.com/80830529/176138275-f0a90ba1-1058-4f98-bcfb-b9532a3b9bb7.png)
