### ISSUE TITLE
[Alex Dominguez]  w4-ETL-Project

### ISSUE THREAD

**Issue by adominguez033** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#3]
https://github.com/adominguez033/Project3_DA_Ironhack

**Comment by Gobuub** [comment]
Al final conseguiste arreglar el problema, cuando me fui decías que ibas a cambiar pero me alegro de que continuaras y fueras capaz de encontrar una solución viable.
Buen trabajo Alex, un readme bastante claro y un repo muy ordenado. Te felicito.
