### ISSUE TITLE
[Oriana Ampuero]  w4-ETL-Project

### ISSUE THREAD

**Issue by OrianAmpuero** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#4]
https://github.com/OrianAmpuero/PROJECT-3.git

**Comment by Gobuub** [comment]
Muy bien ordenado el repo, muy claro y un Readme muy bueno, que facilita la comprensión de todo el trabajo que hay detrás del proyecto, te felicito porque ha sido muy buen trabajo Orianna :)
