### ISSUE TITLE
[JORGE ALBORS]-w4-ETL-Project

### ISSUE THREAD

**Issue by JORGE-SAPIS** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#5]
https://github.com/JORGE-SAPIS/Deep_SentencesETL.git

**Comment by Gobuub** [comment]
El readme es mejorable Jorge, pero bueno es un proyecto al que le veo futuro para el tema de análisis de sentimientos, si quieres puedes seguir con el, más adelante sabrás a que me refiero con el tema de análisis de sentimientos.
