### ISSUE TITLE
[Javi Perez] Proyecto Base de Datos

### ISSUE THREAD

**Issue by JaviPerez23** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#6]
https://github.com/JaviPerez23/Proyecto-3-Creacion-Base-de-Datos.git

**Comment by Gobuub** [comment]
Muy buen trabajo Javi, he visto como has trabajado en el y como has ido sacando todo el curro con esfuerzo, te felicito y te animo a que sigas con el, porque como te hemos comentado creemos que puede tener tirón
