### ISSUE TITLE
[Mau Guerrero]w4-ETL-Project

### ISSUE THREAD

**Issue by maugc1** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#7]
https://github.com/maugc1/3_Proyecto.git

**Comment by Gobuub** [comment]
Te ha faltado el Readme, que está limpio, la idea del Readme es que cuando alguien llegue a tu repo tenga una visión inicial del propósito del mismo, y de como has trabajado en el. Son detallitos que hay que ir puliendo.
