### ISSUE TITLE
[Lucía Martín] w4-ETL- Project

### ISSUE THREAD

**Issue by luciaahab** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#8]
https://github.com/luciaahab/LHOOQ.git

**Comment by Gobuub** [comment]
Es un buen comienzo, no se muy bien cual es la finalidad del proyecto, solo sé que va de arte, pero un readme un poco más explicado me hubiera venido bien para ponerme en contexto, ya sabes a seguir currando, y acabarlo si quieres usar los datos para el proyecto de esta semana.
