### ISSUE TITLE
[Irene Aguerri]  ETL Project

### ISSUE THREAD

**Issue by iaguerri** [Ironhack-Data-Madrid-Mayo-2022/w4-ETL-Project#9]
https://github.com/iaguerri/ETL_ih
Sorry about not having it in Public :(

**Comment by Gobuub** [comment]
Me he hecho gracia el icono del ToDo XDD, hay que tomarse las cosas con filosofía, del trabajo poco puedo añadir porque me has capturado una sopa y poco más, lo bueno es que tienes la semana para ir trabajando en el y usarlo como ha dicho Yona para el proyecto de esta semana.
